# Generated by Django 4.2.1 on 2023-06-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_user_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(upload_to="", verbose_name=""),
        ),
    ]
