# Generated by Django 4.2.1 on 2023-06-23 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_media_file"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FoodMenu",
        ),
    ]
